config/routes.rb
Rails.application.routes.draw do
  resources :managements
  resources :clients
  resources :portfolios
  resources :contactus
  resources :services
  resources :aboutus
  root 'welome#index'

    # root 'projects#index'
    resources :projects
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    


   devise_for :users, controllers: { registrations: "registrations"}

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aboutu.rb
class Aboutu < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contactu.rb
class Contactu < ApplicationRecord
end

app/models/management.rb
class Management < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_aboutu, only: [:show, :edit, :update, :destroy]

  # GET /aboutus
  # GET /aboutus.json
  def index
    @aboutus = Aboutu.all
  end

  # GET /aboutus/1
  # GET /aboutus/1.json
  def show
  end

  # GET /aboutus/new
  def new
    @aboutu = Aboutu.new
  end

  # GET /aboutus/1/edit
  def edit
  end

  # POST /aboutus
  # POST /aboutus.json
  def create
    @aboutu = Aboutu.new(aboutu_params)

    respond_to do |format|
      if @aboutu.save
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully created.' }
        format.json { render :show, status: :created, location: @aboutu }
      else
        format.html { render :new }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aboutus/1
  # PATCH/PUT /aboutus/1.json
  def update
    respond_to do |format|
      if @aboutu.update(aboutu_params)
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutu }
      else
        format.html { render :edit }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutus/1
  # DELETE /aboutus/1.json
  def destroy
    @aboutu.destroy
    respond_to do |format|
      format.html { redirect_to aboutus_url, notice: 'Aboutu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutu
      @aboutu = Aboutu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutu_params
      params.require(:aboutu).permit(:address, :city, :state, :country, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:publishing, :software_products, :training, :clients)
    end
end

app/controllers/welome_controller.rb
class WelomeController < ApplicationController
	
  def index
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welome_helper.rb
module WelomeHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publishing %>
    <%= f.text_field :publishing %>
  </div>

  <div class="field">
    <%= f.label :software_products %>
    <%= f.text_field :software_products %>
  </div>

  <div class="field">
    <%= f.label :training %>
    <%= f.text_field :training %>
  </div>

  <div class="field">
    <%= f.label :clients %>
    <%= f.text_field :clients %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div class="row">
    <div class="col s12"><div class="card red accent-2">
    <div class="card-content">
      <p>There’s a lot of technologies to choose from nowadays. We know a lot of them and our list is increasing.<br>

We believe the most important thing for a software, web and mobile development company is to be able to choose and recommend the right technology mix for the project or product you want to develop. Our approach is project-centric and not technology-centric, we will always find the best technology mix to blend in our services for your software project, web project, mobile project or hybrid project.</p>
    </div>
    <div class="card-tabs">
      <ul class="tabs tabs-fixed-width">
        <li class="tab"><a href="#test4">Web Development</a></li>
        <li class="tab"><a class="active" href="#test5">E-publishing E-Learning</a></li>
        <li class="tab"><a href="#test6">Consultancy</a></li>
      </ul>
    </div>
    <div class="card-content grey lighten-4">
      <div id="test4"><ul class="collapsible popout" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Front End</div>
      <div class="collapsible-body"><span>HTML, CSS, Angular1.x, Angular2.x, Javascript, Bootstrap, MaterializeCSS</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Back End
</div>
      <div class="collapsible-body"><span>Ruby</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Database</div>
      <div class="collapsible-body"><span>Postgresql, Sqlite, Mongodb, Oracle</span></div>
    </li>
  </ul></div>
      <div id="test5"><ul class="collapsible popout" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Branding and strategic thinking</div>
      <div class="collapsible-body"><span>When others focus on just graphic design, we look at your brand’s overall persona and device ways in which the website design can accentuate it online. Our strategy team plays an important role in planning and devising a communication strategy for your website.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Creative web designing
</div>
      <div class="collapsible-body"><span>All our web design projects are directly handled by the senior creative team. The team includes the Art Director, Creative Director and Copywriter – all of whom have over 15 years of expertise in building world-class websites.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Coding and Technology</div>
      <div class="collapsible-body"><span>Our software developers are updated with the latest coding standards and technology innovations in the desktop and mobile medium. This helps us build websites that are highly engaging, secure and in par with the best in the world..</span></div>
    </li>
  </ul></div>
      <div id="test6"><ul class="collapsible popout" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>Branding and strategic thinking</div>
      <div class="collapsible-body"><span>When others focus on just graphic design, we look at your brand’s overall persona and device ways in which the website design can accentuate it online. Our strategy team plays an important role in planning and devising a communication strategy for your website.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Creative web designing
</div>
      <div class="collapsible-body"><span>All our web design projects are directly handled by the senior creative team. The team includes the Art Director, Creative Director and Copywriter – all of whom have over 15 years of expertise in building world-class websites.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Coding and Technology</div>
      <div class="collapsible-body"><span>Our software developers are updated with the latest coding standards and technology innovations in the desktop and mobile medium. This helps us build websites that are highly engaging, secure and in par with the best in the world..</span></div>
    </li>
  </ul></div>
    </div>
  </div></div>
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
  </div>
  <div class="row">
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card">
            <div class="card-image materialboxed">
              <img src="assets/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div></div>
  </div>


<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Publishing</th>
      <th>Software products</th>
      <th>Training</th>
      <th>Clients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.publishing %></td>
        <td><%= service.software_products %></td>
        <td><%= service.training %></td>
        <td><%= service.clients %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publishing:</strong>
  <%= @service.publishing %>
</p>

<p>
  <strong>Software products:</strong>
  <%= @service.software_products %>
</p>

<p>
  <strong>Training:</strong>
  <%= @service.training %>
</p>

<p>
  <strong>Clients:</strong>
  <%= @service.clients %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>