config/routes.rb
Rails.application.routes.draw do
  resources :managements
  resources :clients
  resources :portfolios
  resources :contactus
  resources :services
  resources :aboutus
  root 'welome#index'

    # root 'projects#index'
    resources :projects
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    


   devise_for :users, controllers: { registrations: "registrations"}

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aboutu.rb
class Aboutu < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contactu.rb
class Contactu < ApplicationRecord
end

app/models/management.rb
class Management < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_aboutu, only: [:show, :edit, :update, :destroy]

  # GET /aboutus
  # GET /aboutus.json
  def index
    @aboutus = Aboutu.all
  end

  # GET /aboutus/1
  # GET /aboutus/1.json
  def show
  end

  # GET /aboutus/new
  def new
    @aboutu = Aboutu.new
  end

  # GET /aboutus/1/edit
  def edit
  end

  # POST /aboutus
  # POST /aboutus.json
  def create
    @aboutu = Aboutu.new(aboutu_params)

    respond_to do |format|
      if @aboutu.save
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully created.' }
        format.json { render :show, status: :created, location: @aboutu }
      else
        format.html { render :new }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aboutus/1
  # PATCH/PUT /aboutus/1.json
  def update
    respond_to do |format|
      if @aboutu.update(aboutu_params)
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutu }
      else
        format.html { render :edit }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutus/1
  # DELETE /aboutus/1.json
  def destroy
    @aboutu.destroy
    respond_to do |format|
      format.html { redirect_to aboutus_url, notice: 'Aboutu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutu
      @aboutu = Aboutu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutu_params
      params.require(:aboutu).permit(:address, :city, :state, :country, :phone)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/welome_controller.rb
class WelomeController < ApplicationController
	
  def index
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welome_helper.rb
module WelomeHelper
end

app/views/aboutus/_form.html.erb
<%= form_for(aboutu) do |f| %>
  <% if aboutu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aboutu.errors.count, "error") %> prohibited this aboutu from being saved:</h2>

      <ul>
      <% aboutu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aboutus/edit.html.erb
<h1>Editing Aboutu</h1>

<%= render 'form', aboutu: @aboutu %>

<%= link_to 'Show', @aboutu %> |
<%= link_to 'Back', aboutus_path %>

app/views/aboutus/index.html.erb
  <div class="row">
    <div class="col s12 m6 l3"><div class="card red darken-1">
            <div class="card-content white-text">
              <span class="card-title">About us</span>
              <p>GA solutions, is relying on a optimal strategy, which propound a propitious milieu for the most renowned service providers in IT Outsourcing, Publishing and E-governance projects and publications. we make websites that succeed and boost revenue. Constantly delivering effective e-commerce designs and solutions that are the back bone of many successful online businesses.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card pink darken-1">
            <div class="card-content white-text">
              <span class="card-title">What we Do</span>
              <p>Since the year of inception, GA solutions proudly boasts to have each of our client’s happy! We indulge in mind-blowing Web Designing and a Development solutions that help your business succeed online, increasing sales, profits, and overall ROI.Our trusted and efficient service, gives us an extra edge over our competitors.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
              <a href="#">This is a link</a>
            </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Our Development Area</span>
              <p>We are proud to claim ourselves as a professional full service website services company positioned in Chennai, India. We have been recognized as one of the best website design & e-commerce web design, web development, & web application developers in the industry.We have the skills and capacity to work with you to meet your requirements.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
              <a href="#">This is a link</a>
            </div>
          </div></div>
      <div class="col s12 m6 l3"><div class="card amber lighten-1 darken-1">
            <div class="card-content white-text">
              <span class="card-title">Technical skills</span>
              <p> Ruby Portal Development, Website redesign, e-commerce website development, CMS based website development, brochure design, PSD to XHTML conversion, web application services, Mobile application development services and Digital marketing services for reasonable rates in Karaikudi</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
              <a href="#">This is a link</a>
            </div>
          </div></div>
  </div>


<p id="notice"><%= notice %></p>

<h1>Aboutus</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aboutus.each do |aboutu| %>
      <tr>
        <td><%= aboutu.address %></td>
        <td><%= aboutu.city %></td>
        <td><%= aboutu.state %></td>
        <td><%= aboutu.country %></td>
        <td><%= aboutu.phone %></td>
        <td><%= link_to 'Show', aboutu %></td>
        <td><%= link_to 'Edit', edit_aboutu_path(aboutu) %></td>
        <td><%= link_to 'Destroy', aboutu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aboutu', new_aboutu_path %>

app/views/aboutus/new.html.erb
<h1>New Aboutu</h1>

<%= render 'form', aboutu: @aboutu %>

<%= link_to 'Back', aboutus_path %>

app/views/aboutus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @aboutu.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @aboutu.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @aboutu.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @aboutu.country %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @aboutu.phone %>
</p>

<%= link_to 'Edit', edit_aboutu_path(@aboutu) %> |
<%= link_to 'Back', aboutus_path %>

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
  <div class="row">
      <div class="col s12 m5 l12">
        <div class="card-panel teal">
          <span class="white-text">I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively. I am similar to what is called a panel in other frameworks.
          </span>
        </div>
      </div>
    </div>
  <div class="row"><marquee>
    <div class="col s12 m6 l3"><div class="card red darken-1">
     <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="assets/office.jpg">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
          <p><a href="#">This is a link</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
          <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
      </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card pink darken-1">
 <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="assets/office.jpg">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
          <p><a href="#">This is a link</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
          <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
      </div>
          </div></div>
    <div class="col s12 m6 l3"><div class="card grey darken-1">
 <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="assets/office.jpg">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
          <p><a href="#">This is a link</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
          <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
      </div>
          </div></div>
      <div class="col s12 m6 l3"><div class="card amber lighten-1 darken-1">
 <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="assets/office.jpg">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
          <p><a href="#">This is a link</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
          <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
      </div>
          </div></div></marquee>
  </div>
  <div class="row">
      <div class="col s12 m5 l12">
        <div class="card-panel teal">
          <span class="white-text">I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively. I am similar to what is called a panel in other frameworks.
          </span>
        </div>
      </div>
    </div>
<!-- <div class="row">
  <div class="l6">
    <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="assets/office.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
      <p><a href="#">This is a link</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>
<div> -->

<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.image %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @client.image %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>