config/routes.rb
Rails.application.routes.draw do
  resources :managements
  resources :clients
  resources :portfolios
  resources :contactus
  resources :services
  resources :aboutus
  root 'welome#index'

    # root 'projects#index'
    resources :projects
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    


   devise_for :users, controllers: { registrations: "registrations"}

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aboutu.rb
class Aboutu < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contactu.rb
class Contactu < ApplicationRecord
end

app/models/management.rb
class Management < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_aboutu, only: [:show, :edit, :update, :destroy]

  # GET /aboutus
  # GET /aboutus.json
  def index
    @aboutus = Aboutu.all
  end

  # GET /aboutus/1
  # GET /aboutus/1.json
  def show
  end

  # GET /aboutus/new
  def new
    @aboutu = Aboutu.new
  end

  # GET /aboutus/1/edit
  def edit
  end

  # POST /aboutus
  # POST /aboutus.json
  def create
    @aboutu = Aboutu.new(aboutu_params)

    respond_to do |format|
      if @aboutu.save
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully created.' }
        format.json { render :show, status: :created, location: @aboutu }
      else
        format.html { render :new }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aboutus/1
  # PATCH/PUT /aboutus/1.json
  def update
    respond_to do |format|
      if @aboutu.update(aboutu_params)
        format.html { redirect_to @aboutu, notice: 'Aboutu was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutu }
      else
        format.html { render :edit }
        format.json { render json: @aboutu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutus/1
  # DELETE /aboutus/1.json
  def destroy
    @aboutu.destroy
    respond_to do |format|
      format.html { redirect_to aboutus_url, notice: 'Aboutu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutu
      @aboutu = Aboutu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutu_params
      params.require(:aboutu).permit(:address, :city, :state, :country, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_management, only: [:show, :edit, :update, :destroy]

  # GET /managements
  # GET /managements.json
  def index
    @managements = Management.all
  end

  # GET /managements/1
  # GET /managements/1.json
  def show
  end

  # GET /managements/new
  def new
    @management = Management.new
  end

  # GET /managements/1/edit
  def edit
  end

  # POST /managements
  # POST /managements.json
  def create
    @management = Management.new(management_params)

    respond_to do |format|
      if @management.save
        format.html { redirect_to @management, notice: 'Management was successfully created.' }
        format.json { render :show, status: :created, location: @management }
      else
        format.html { render :new }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managements/1
  # PATCH/PUT /managements/1.json
  def update
    respond_to do |format|
      if @management.update(management_params)
        format.html { redirect_to @management, notice: 'Management was successfully updated.' }
        format.json { render :show, status: :ok, location: @management }
      else
        format.html { render :edit }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managements/1
  # DELETE /managements/1.json
  def destroy
    @management.destroy
    respond_to do |format|
      format.html { redirect_to managements_url, notice: 'Management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_management
      @management = Management.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def management_params
      params.require(:management).permit(:present, :in_time, :out_time, :target, :page_processed, :page_error)
    end
end

app/controllers/welome_controller.rb
class WelomeController < ApplicationController
	
  def index
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welome_helper.rb
module WelomeHelper
end

app/views/managements/_form.html.erb
<%= form_for(management) do |f| %>
  <% if management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(management.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :present %>
    <%= f.check_box :present %>
  </div>

  <div class="field">
    <%= f.label :in_time %>
    <%= f.date_select :in_time %>
  </div>

  <div class="field">
    <%= f.label :out_time %>
    <%= f.date_select :out_time %>
  </div>

  <div class="field">
    <%= f.label :target %>
    <%= f.number_field :target %>
  </div>

  <div class="field">
    <%= f.label :page_processed %>
    <%= f.number_field :page_processed %>
  </div>

  <div class="field">
    <%= f.label :page_error %>
    <%= f.number_field :page_error %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managements/edit.html.erb
<h1>Editing Management</h1>

<%= render 'form', management: @management %>

<%= link_to 'Show', @management %> |
<%= link_to 'Back', managements_path %>

app/views/managements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managements</h1>

<table>
  <thead>
    <tr>
      <th>Present</th>
      <th>In time</th>
      <th>Out time</th>
      <th>Target</th>
      <th>Page processed</th>
      <th>Page error</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managements.each do |management| %>
      <tr>
        <td><%= management.present %></td>
        <td><%= management.in_time %></td>
        <td><%= management.out_time %></td>
        <td><%= management.target %></td>
        <td><%= management.page_processed %></td>
        <td><%= management.page_error %></td>
        <td><%= link_to 'Show', management %></td>
        <td><%= link_to 'Edit', edit_management_path(management) %></td>
        <td><%= link_to 'Destroy', management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Management', new_management_path %>

app/views/managements/new.html.erb
<h1>New Management</h1>

<%= render 'form', management: @management %>

<%= link_to 'Back', managements_path %>

app/views/managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Present:</strong>
  <%= @management.present %>
</p>

<p>
  <strong>In time:</strong>
  <%= @management.in_time %>
</p>

<p>
  <strong>Out time:</strong>
  <%= @management.out_time %>
</p>

<p>
  <strong>Target:</strong>
  <%= @management.target %>
</p>

<p>
  <strong>Page processed:</strong>
  <%= @management.page_processed %>
</p>

<p>
  <strong>Page error:</strong>
  <%= @management.page_error %>
</p>

<%= link_to 'Edit', edit_management_path(@management) %> |
<%= link_to 'Back', managements_path %>